[LIVY-708][SERVER] Align curator jars version
## What changes were proposed in this pull request?
Livy server has dependency of Apache Curator through hadoop client. However, the versions of the curator jars are not aligned. Here're the curator jars after build

* curator-client-2.7.1.jar
* curator-framework-2.7.1.jar
* curator-recipes-2.6.0.jar
This will cause Method not found issue in some case:
```
Exception in thread "main" java.lang.NoSuchMethodError:
org.apache.curator.utils.PathUtils.validatePath(Ljava/lang/String;)V
```
This patch specify the version of curator-recipes to 2.7.1.

## How was this patch tested?
Manually test in the env where no such method exception are thrown.
Existing UT/IT

Author: yihengwang <yihengwang@tencent.com>

Closes #256 from yiheng/fix_708.